services:
  frontend:
    image: node
    container_name: frontend
    command: [ "sh", "-c", "npm install && npm run dev"]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - ft_transcendence-network
    working_dir: /app
    depends_on:
      - backend
  backend:
    image: node:20-alpine
    container_name: backend
    ports:
      - "8080:8080"
    command: [ "sh", "-c", "npm rebuild && npm install && npm run dev"] 
    networks:
      - ft_transcendence-network
    volumes:
      - ./backend:/app
      - ./database:/root/db
    working_dir: /app
    depends_on:
      - database
  database:
    image: alpine:latest
    container_name: database
    command: ["sh", "-c", "apk add --no-cache sqlite && mkdir -p /root/db && touch /root/db/database.db && echo 'Database ready' && tail -f /dev/null"]
    networks:
      - ft_transcendence-network
    volumes:
      - ./database:/root/db
    restart: always

  # You also need to setup a reverse proxy like nginx, traeffik, or caddy
  # To access the website only in port 80 or 443
  # This will be used for production builds

networks:
  ft_transcendence-network:
    driver: bridge